//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaloniaClipboard.Styles.Resources.Languages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AvaloniaClipboard.Styles.Resources.Languages.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ToGlobalClipboard {
            get {
                return ResourceManager.GetString("ToGlobalClipboard", resourceCulture);
            }
        }
        
        public static string ToLocalClipboard {
            get {
                return ResourceManager.GetString("ToLocalClipboard", resourceCulture);
            }
        }
        
        public static string KeysToGlobalClipboard {
            get {
                return ResourceManager.GetString("KeysToGlobalClipboard", resourceCulture);
            }
        }
        
        public static string KeysToLocalClipboard {
            get {
                return ResourceManager.GetString("KeysToLocalClipboard", resourceCulture);
            }
        }
        
        public static string SaveBoards {
            get {
                return ResourceManager.GetString("SaveBoards", resourceCulture);
            }
        }
        
        public static string AddBoardAndHotkey {
            get {
                return ResourceManager.GetString("AddBoardAndHotkey", resourceCulture);
            }
        }
        
        public static string RemoveBoardAndHotkey {
            get {
                return ResourceManager.GetString("RemoveBoardAndHotkey", resourceCulture);
            }
        }
        
        public static string RefreshWatchList {
            get {
                return ResourceManager.GetString("RefreshWatchList", resourceCulture);
            }
        }
        
        public static string RunStop {
            get {
                return ResourceManager.GetString("RunStop", resourceCulture);
            }
        }
        
        public static string ClearForm {
            get {
                return ResourceManager.GetString("ClearForm", resourceCulture);
            }
        }
        
        public static string HotkeyTab {
            get {
                return ResourceManager.GetString("HotkeyTab", resourceCulture);
            }
        }
        
        public static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        public static string WatchTab {
            get {
                return ResourceManager.GetString("WatchTab", resourceCulture);
            }
        }
        
        public static string BoardTab {
            get {
                return ResourceManager.GetString("BoardTab", resourceCulture);
            }
        }
        
        public static string ReadBoards {
            get {
                return ResourceManager.GetString("ReadBoards", resourceCulture);
            }
        }
    }
}
